# Generated by Django 6.0.7 on 2026-07-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('brand', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('origin', models.CharField(max_length=128)),
                ('mint_date', models.DateField()),
                ('nfc_chip', models.CharField(max_length=128)),
                ('blockchain_hash', models.CharField(max_length=128)),
                ('block_number', models.BigIntegerField(default=1894204)),
                ('smart_contract', models.CharField(default='0x71C7656EC7ab88b098defB751B7401B5f6d8976F', max_length=128)),
                ('warranty', models.CharField(max_length=256)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_queried', models.CharField(max_length=64)),
                ('is_authentic', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
